import type { Metadata } from "next";
import "./globals.css";
import Hero from "../../components/Hero";
import Navbar from "../../components/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
              <Hero/>
            </div>
            <div>
              <Navbar/>
            </div>
        {children}
      </body>
    </html>
  );
}
